load("@rules_cc//cc:defs.bzl", "cc_library")


cc_library(
    name = "fe_lens",
    hdrs = ["fe_lens.hpp"],
    srcs = ["fe_lens.cpp"],
    deps = [
        "@opencv//:opencv",
    ],
    visibility = ["//visibility:public"],
)